[book]
authors = ["Tom Vloet"]
description = "Sea cleaner, a simple game based on Yaeger "
language = "en"
multilingual = false
src = "docs"
title = "Sea Cleaner"

[build]
build-dir = "target/docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/tvloet1/seacleaner"
